### ISSUE TITLE
Using together with MUI in NextJS

### ISSUE THREAD

**Issue by titocosta** [chatscope/chat-ui-kit-styles#10]
The svg icons in `Searchbar` and `MessageInput` (in `SendButton`) appear of wrong size or misaligned position when using chat-ui-kit as part of a NextJS app using the MUI material UI library and its baseline css theming.

I've tried using `<StyledEngineProvider injectFirst>` as described at [MUI style interoperability guide](https://mui.com/material-ui/guides/interoperability/#global-css), but still could not fix issue.

Any idea on what css attribute could be creating the conflict?

**Comment by supersnager** [comment]
@titocosta I'm not using MUI, so I have no idea :).

But you can inspect the icon using dev tools and check what style is set on it.
If you find something, please share it here.

**Comment by titocosta** [comment]
The cause of my problem was related to getting FontAwesome to work with NextJS. The solution as described in the [FontAwesome docs](https://fontawesome.com/docs/web/use-with/react/use-with) is to add the below to `pages/_app.tsx`:

```
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
config.autoAddCss = false
```

**Comment by supersnager** [comment]
Thanks @titocosta !
