### ISSUE TITLE
Not able to locate "@chatscope/chat-ui-kit-styles/dist/default/styles.min.css" file

### ISSUE THREAD

**Issue by shahid-ics** [chatscope/chat-ui-kit-styles#14]

**Comment by supersnager** [comment]
@shahid-ics Please provide more information.

- what framework you use,
- how you import styles,
-  do you installed [@chatscope/chat-ui-kit-styles](https://github.com/chatscope/chat-ui-kit-styles) library

**Comment by supersnager** [comment]
Closed due to inactivity

**Comment by samuelschnurr** [comment]
Hello.

I had the same problem. My setup was Create-React-App (CRA) with TypeScript.

The import from the ReadMe does work for .js and .jsx. But .ts/tsx files are not able to import it in this way by default:

`import styles from '@chatscope/chat-ui-kit-styles/dist/default/styles.min.css`

Instead the file can be imported in *.tsx with this:

`import "@chatscope/chat-ui-kit-styles/dist/default/styles.min.css"`

Also see other ways in combination with webpack etc. from this link:

https://medium.com/@sapegin/css-modules-with-typescript-and-webpack-6b221ebe5f10

**Comment by supersnager** [comment]
Thanks @samuelschnurr!
