### ISSUE TITLE
Wrapped input spills over container with long message in it

### ISSUE THREAD

**Issue by yevhen-logosha** [chatscope/chat-ui-kit-styles#4]
@supersnager got one more mate. :) 
if you go to https://chatscope.io/storybook/react/?path=/docs/components-chatcontainer--wrapped-message-input
and type in really looooooong message, input pushes buttons beyond container. Looks like setting `width: 50%` on input if its wrapped resolves issue.

**Comment by supersnager** [comment]
@yevhen-logosha Thank you for reporting this.
It was not a bug in the components css, but in the styling of the story. The Storybook on the website is now fixed.

**Comment by yevhen-logosha** [comment]
@supersnager just fyi, was able to reproduce it, link to storybook was just as a reference ;)
